#!/bin/bash
# Fail on any error
set -e
set -o pipefail

echo "Starting Kokoro release build script"

# Source the common build logic.
source "${KOKORO_PIPER_DIR}/google3/third_party/py/google_cloud_mldiagnostics/kokoro/common_build.sh"

# Define variables specific to this build.
COPYBARA_SKY="${KOKORO_PIPER_DIR}/google3/third_party/py/google_cloud_mldiagnostics/copy.bara.sky"
OUTPUT_DIR=$(mktemp -d)
trap 'rm -rf "${OUTPUT_DIR}"' EXIT

# 1. Setup Java environment.
setup_java

# 2. Run CopyBara to generate OSS source.
run_copybara "${COPYBARA_SKY}" "${OUTPUT_DIR}"

# 3. Build the package and copy artifacts.
build_and_copy_artifacts "${OUTPUT_DIR}"

# TODO: Add automated tests here (e.g., smoke tests) before publishing.

# Set up credentials for Twine (Token authentication)
export TWINE_USERNAME="__token__"
export TWINE_NON_INTERACTIVE=1

echo "Installing twine..."
python -m pip install twine

echo "Publishing to PyPI..."
# TWINE_PASSWORD must be set in the environment via Kokoro Keystore/UI
python -m twine upload "${KOKORO_ARTIFACTS_DIR}/dist/*"
echo "Successfully uploaded to PyPI! You can check the history at: https://pypi.org/project/google-cloud-mldiagnostics/#history"

# Phase 2: MOSS Compliance & Staging (Commented out for direct PyPI release)
# echo "Phase 2: MOSS Compliance & Staging"
# # TODO: Push to Artifact Registry staging for MOSS Exit Gate
# # Note: SBOMs are automatically generated by SCAN_ARTIFACTS and placed alongside artifacts

echo "Release build script completed successfully"
